using Program_Files.Classes;
using Program_Files.Dashboard;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace Program_Files
{
    public partial class AddEmployee : Form
    {
        private AdminDashboard adminDashboard;

        private string EmployeeId {  get; set; }    
        private string Password { get; set; }   
       
        public AddEmployee()
        {
            InitializeComponent();
           // this.AutoGeneratedID();
           this.PopulateGridview();
           
        }
        public AddEmployee(AdminDashboard adminDashboard) : this()
        {
            this.adminDashboard = adminDashboard;   

            
        }

        private void AutoGeneratedID()
        {
            string query = "Select Top 1 UserID from UserTB Order By SerialNo DESC";
            string id = DBAccess.ExecuteQuery(query).Rows[0][0].ToString();
            string[] no = id.Split('-'); 
            int serial = Convert.ToInt32(no[2]);
            ++serial;

            this.EmployeeId = "E-" + txtLastName.Text+"-"+serial;

           

        }

        private void PopulateGridview(string query = "Select UserID,FirstName,LastName,Email,PhoneNumber,Nid,Gender,Age,Dob,JoiningDate,Salary,Address,ASsignedBy from UserTB where Role = 'Employee' ")
        {
            DataTable dt = DBAccess.ExecuteQuery(query);
            dgvShowEmployee.DataSource = dt;

        }

        private bool IsValid()
        {
            bool valid = true;
            
            foreach(Control control in Controls)
            {
                if(control is TextBox && control.Text.Length == 0)
                {
                    valid = false; break;
                }
                else if(control is ComboBox && control.Text.Length == 0)
                {
                    valid = false; break;    
                }
            }
            return valid;
        }

        private void AutoGeneratedPassword()
        {
            this.Password = "E-" + this.txtLastName.Text + "@" + this.EmployeeId + "-" + this.cmbAge.Text + "P@$$word";
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {

            try
            {
                if (this.IsValid())
                {
                    this.AutoGeneratedID();
                    this.AutoGeneratedPassword();
                    string query = "insert into UserTB values('" + this.EmployeeId + "','" + this.txtFirstName.Text + "','" + this.txtLastName.Text + "','" + this.txtEmail.Text + "','" + this.PhoneTxt.Text + "','" + this.txtNid.Text + "','" + cmbGender.Text + "'," + Convert.ToInt32(cmbAge.Text) + ",'" + this.DOBDtp.Text + "','" + this.JoindateDtp.Text + "'," + Convert.ToInt32(this.SalTxt.Text) + ",'" + this.AddressTxt.Text + "','"+this.adminDashboard.User.UserName+"','" + this.Password + "','Employee') ";
                    int rowAffecyted = DBAccess.ExecuteDMLQuery(query);

                    if (rowAffecyted > 0)
                    {
                        MessageBox.Show("Employee Added Succesfully\n\nPassword : " + this.Password + "\n\nUser ID : " + this.UserId);
                        this.PopulateGridview();

                    }
                    else
                    {
                        MessageBox.Show("Cant Inssert Data", "ERROR", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

                else
                {
                    MessageBox.Show("PLease Enter all information");
                }
            }
            catch (Exception ex) { MessageBox.Show(ex.Message); }
        }

        private void AddEmployee_Load(object sender, EventArgs e)
        {

        }

        private void EmpInsertCrossBtn_Click(object sender, EventArgs e)
        {
            Application.Exit(); 
        }

        private void BackBtn_Click(object sender, EventArgs e)
        {
            this.adminDashboard.Show();
            this.Hide();
        }
    }
}
